# Generated by Django 4.2.6 on 2023-11-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match1Content', models.CharField(max_length=20)),
                ('match2Content', models.CharField(max_length=20)),
                ('match3Content', models.CharField(max_length=20)),
                ('match4Content', models.CharField(max_length=20)),
                ('match5Content', models.CharField(max_length=20)),
                ('match6Content', models.CharField(max_length=20)),
                ('match7Content', models.CharField(max_length=20)),
                ('match8Content', models.CharField(max_length=20)),
                ('match9Content', models.CharField(max_length=20)),
                ('match10Content', models.CharField(max_length=20)),
                ('level1Content', models.CharField(max_length=20)),
                ('level2Content', models.CharField(max_length=20)),
                ('level3Content', models.CharField(max_length=20)),
                ('level4Content', models.CharField(max_length=20)),
                ('level5Content', models.CharField(max_length=20)),
                ('level6Content', models.CharField(max_length=20)),
                ('level7Content', models.CharField(max_length=20)),
                ('level8Content', models.CharField(max_length=20)),
                ('level9Content', models.CharField(max_length=20)),
                ('level10Content', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droppable1Content', models.CharField(max_length=20)),
                ('droppable2Content', models.CharField(max_length=20)),
                ('droppable3Content', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('goodsID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('goodsA', models.CharField(max_length=20)),
                ('goods1', models.CharField(max_length=20)),
                ('goodsB', models.CharField(max_length=20)),
                ('goods2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.CharField(default='default_value', max_length=100)),
                ('x2', models.CharField(default='default_value', max_length=100)),
                ('x3', models.CharField(default='default_value', max_length=100)),
                ('x4', models.CharField(default='default_value', max_length=100)),
                ('x5', models.CharField(default='default_value', max_length=100)),
                ('x6', models.CharField(default='default_value', max_length=100)),
                ('x7', models.CharField(default='default_value', max_length=100)),
                ('x8', models.CharField(default='default_value', max_length=100)),
                ('x9', models.CharField(default='default_value', max_length=100)),
                ('x10', models.CharField(default='default_value', max_length=100)),
                ('x11', models.CharField(default='default_value', max_length=100)),
                ('x12', models.CharField(default='default_value', max_length=100)),
                ('x13', models.CharField(default='default_value', max_length=100)),
                ('x14', models.CharField(default='default_value', max_length=100)),
                ('x15', models.CharField(default='default_value', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_psw', models.CharField(max_length=20)),
            ],
        ),
    ]
