# Generated by Django 4.2.6 on 2023-11-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_newmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droppable1Content', models.CharField(max_length=20)),
                ('droppable2Content', models.CharField(max_length=20)),
                ('droppable3Content', models.CharField(max_length=20)),
                ('droppable4Content', models.CharField(max_length=20)),
                ('droppable5Content', models.CharField(max_length=20)),
                ('droppable6Content', models.CharField(max_length=20)),
                ('droppable7Content', models.CharField(max_length=20)),
                ('droppable8Content', models.CharField(max_length=20)),
                ('droppable9Content', models.CharField(max_length=20)),
                ('droppable10Content', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ranking',
        ),
    ]
