# Generated by Django 4.2.6 on 2023-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='newresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_score', models.CharField(default='default_value', max_length=100)),
                ('end_score', models.CharField(default='default_value', max_length=100)),
            ],
        ),
    ]
